"""add unique constraint to workspace members

Revision ID: 3c23346c0b34
Revises: ec3215359c2c
Create Date: 2026-07-10 10:04:00.284072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c23346c0b34'
down_revision: Union[str, Sequence[str], None] = 'ec3215359c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_workspace_member', 'workspace_members', ['workspace_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workspace_member', 'workspace_members', type_='unique')
    # ### end Alembic commands ###
