"""add deleted_at to tasks

Revision ID: 60ad4e71e38d
Revises: 824b209c9958
Create Date: 2026-07-10 21:08:28.524606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ad4e71e38d'
down_revision: Union[str, Sequence[str], None] = '824b209c9958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deleted_at')
    # ### end Alembic commands ###
